# Generated by Django 4.2 on 2023-10-13 18:22

from django.db import migrations, models
import wallpaper.bannermodels


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='image_path',
        ),
        migrations.AddField(
            model_name='banners',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=wallpaper.bannermodels.upload_to),
        ),
    ]
